/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sql_java_oh_no;

import javax.swing.*;
import java.sql.*;      

public class login extends DBConnect {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        DoConnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        invalid = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        password_txt = new javax.swing.JPasswordField();
        login_finish_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        login_finish_btn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(24, 64, 126));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        invalid.setBackground(new java.awt.Color(105, 73, 50));
        invalid.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        invalid.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(invalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 320, 26));

        email_txt.setBackground(new java.awt.Color(204, 204, 204));
        email_txt.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        email_txt.setText("Email");
        email_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                email_txtMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                email_txtMouseReleased(evt);
            }
        });
        email_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txtActionPerformed(evt);
            }
        });
        email_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                email_txtKeyReleased(evt);
            }
        });
        jPanel2.add(email_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 360, 50));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 60)); // NOI18N
        jLabel3.setText("Log In");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        password_txt.setBackground(new java.awt.Color(204, 204, 204));
        password_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        password_txt.setText("password");
        password_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                password_txtMouseClicked(evt);
            }
        });
        password_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_txtActionPerformed(evt);
            }
        });
        jPanel2.add(password_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 360, 50));

        login_finish_btn.setBackground(new java.awt.Color(0, 0, 0));
        login_finish_btn.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        login_finish_btn.setForeground(new java.awt.Color(255, 255, 255));
        login_finish_btn.setText("Return");
        login_finish_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_finish_btnActionPerformed(evt);
            }
        });
        jPanel2.add(login_finish_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 152, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("forgot password?");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jLabel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel1PropertyChange(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Sign up");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login-avatar.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("or");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, -1, 20));

        login_finish_btn1.setBackground(new java.awt.Color(0, 0, 0));
        login_finish_btn1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        login_finish_btn1.setForeground(new java.awt.Color(255, 255, 255));
        login_finish_btn1.setText("Log In");
        login_finish_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_finish_btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(login_finish_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 152, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void login_finish_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_finish_btnActionPerformed
 gui mainmenu = new gui();
        this.dispose();
        mainmenu.setVisible(true);        
    }//GEN-LAST:event_login_finish_btnActionPerformed

    private void email_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txtActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       sign_in mainmenu = new sign_in();
        this.dispose();
        mainmenu.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void password_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_txtActionPerformed

    private void email_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_email_txtMouseClicked
      email_txt.setText(null);
    }//GEN-LAST:event_email_txtMouseClicked

    private void password_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_password_txtMouseClicked
      password_txt.setText(null);
    }//GEN-LAST:event_password_txtMouseClicked

    private void email_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_email_txtKeyReleased

    }//GEN-LAST:event_email_txtKeyReleased

    private void email_txtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_email_txtMouseReleased

    }//GEN-LAST:event_email_txtMouseReleased

    private void jLabel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1PropertyChange

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
     view_pass mainmenu = new view_pass();
        this.dispose();
        mainmenu.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void login_finish_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_finish_btn1ActionPerformed
    String email = email_txt.getText().trim();
String password = password_txt.getText();
invalid.setText("");

if (email.isEmpty() || password.isEmpty()) {
    invalid.setText("Email or Password is Invalid!");
    return;
}

try {
    String loginQuery = "SELECT * FROM users WHERE EMAIL = ? AND PASSWORD = ?";
    PreparedStatement pstmt = con.prepareStatement(loginQuery);
    pstmt.setString(1, email);
    pstmt.setString(2, password);
    ResultSet rs = pstmt.executeQuery();

    if (rs.next()) {
        int userId = rs.getInt("user_id");

        
        to_do_list mainmenu = new to_do_list(userId); 
        this.dispose();
        mainmenu.setVisible(true);
    } else {
        invalid.setText("Email or Password is Invalid!");
    }

    rs.close();
    pstmt.close();

} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
    e.printStackTrace();
}
    }//GEN-LAST:event_login_finish_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email_txt;
    private javax.swing.JLabel invalid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login_finish_btn;
    private javax.swing.JButton login_finish_btn1;
    private javax.swing.JPasswordField password_txt;
    // End of variables declaration//GEN-END:variables
}
