/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sql_java_oh_no;

import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author nejac
 */
public class sign_in extends DBConnect {

     public String currentans;
    public sign_in() {
        initComponents();
        DoConnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        contactnum_label = new javax.swing.JLabel();
        contactnum = new javax.swing.JTextField();
        return_btn = new javax.swing.JButton();
        signup_finish_btn = new javax.swing.JButton();
        address_txt = new javax.swing.JTextField();
        email_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        password_label1 = new javax.swing.JLabel();
        password_label2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        sec_ans = new javax.swing.JTextField();
        password_txt = new javax.swing.JPasswordField();
        password_confirm_txt = new javax.swing.JPasswordField();
        lname = new javax.swing.JTextField();
        lastname_label = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        invalid_email = new javax.swing.JLabel();
        email_label = new javax.swing.JLabel();
        address_label = new javax.swing.JLabel();
        password_label3 = new javax.swing.JLabel();
        firstname_label1 = new javax.swing.JLabel();
        invalid_password = new javax.swing.JLabel();
        invalid_confirm = new javax.swing.JLabel();
        invalid_sec = new javax.swing.JLabel();
        invalid_address = new javax.swing.JLabel();
        invalid_name = new javax.swing.JLabel();
        invalid_contact = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(24, 64, 126));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contactnum_label.setBackground(new java.awt.Color(105, 73, 50));
        contactnum_label.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        contactnum_label.setText("Contact No. (Phone):");
        jPanel2.add(contactnum_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 180, 20));

        contactnum.setBackground(new java.awt.Color(204, 204, 204));
        contactnum.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        contactnum.setForeground(new java.awt.Color(105, 73, 50));
        contactnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactnumActionPerformed(evt);
            }
        });
        contactnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contactnumKeyReleased(evt);
            }
        });
        jPanel2.add(contactnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 320, -1));

        return_btn.setBackground(new java.awt.Color(0, 0, 0));
        return_btn.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        return_btn.setForeground(new java.awt.Color(255, 255, 255));
        return_btn.setText("Return");
        return_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_btnActionPerformed(evt);
            }
        });
        jPanel2.add(return_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 140, 40));

        signup_finish_btn.setBackground(new java.awt.Color(0, 0, 0));
        signup_finish_btn.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        signup_finish_btn.setForeground(new java.awt.Color(255, 255, 255));
        signup_finish_btn.setText("Finish");
        signup_finish_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_finish_btnActionPerformed(evt);
            }
        });
        jPanel2.add(signup_finish_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 140, 40));

        address_txt.setBackground(new java.awt.Color(204, 204, 204));
        address_txt.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        address_txt.setForeground(new java.awt.Color(105, 73, 50));
        address_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_txtActionPerformed(evt);
            }
        });
        jPanel2.add(address_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 320, -1));

        email_txt.setBackground(new java.awt.Color(204, 204, 204));
        email_txt.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        email_txt.setForeground(new java.awt.Color(105, 73, 50));
        email_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txtActionPerformed(evt);
            }
        });
        jPanel2.add(email_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 320, -1));

        jLabel3.setBackground(new java.awt.Color(105, 73, 50));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setText("Sign Up");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        password_label1.setBackground(new java.awt.Color(105, 73, 50));
        password_label1.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        password_label1.setText("Password:");
        jPanel2.add(password_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        password_label2.setBackground(new java.awt.Color(105, 73, 50));
        password_label2.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        password_label2.setText("Confirm Password:");
        jPanel2.add(password_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox1.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your favorite thing?", "What is your mother's maiden name?", "Where did you graduate (high school / college)?" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 320, 20));

        sec_ans.setBackground(new java.awt.Color(204, 204, 204));
        sec_ans.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        sec_ans.setForeground(new java.awt.Color(105, 73, 50));
        sec_ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec_ansActionPerformed(evt);
            }
        });
        jPanel2.add(sec_ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 320, -1));

        password_txt.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(password_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 320, -1));

        password_confirm_txt.setBackground(new java.awt.Color(204, 204, 204));
        password_confirm_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_confirm_txtActionPerformed(evt);
            }
        });
        jPanel2.add(password_confirm_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 320, -1));

        lname.setBackground(new java.awt.Color(204, 204, 204));
        lname.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        lname.setForeground(new java.awt.Color(105, 73, 50));
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        jPanel2.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 150, -1));

        lastname_label.setBackground(new java.awt.Color(105, 73, 50));
        lastname_label.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        lastname_label.setText("Last Name:");
        jPanel2.add(lastname_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 100, -1));

        fname.setBackground(new java.awt.Color(204, 204, 204));
        fname.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        fname.setForeground(new java.awt.Color(105, 73, 50));
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        jPanel2.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 150, -1));

        invalid_email.setBackground(new java.awt.Color(105, 73, 50));
        invalid_email.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        invalid_email.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(invalid_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 233, 20));

        email_label.setBackground(new java.awt.Color(105, 73, 50));
        email_label.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        email_label.setText("Email:");
        jPanel2.add(email_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 50, -1));

        address_label.setBackground(new java.awt.Color(105, 73, 50));
        address_label.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        address_label.setText("Address:");
        jPanel2.add(address_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        password_label3.setBackground(new java.awt.Color(105, 73, 50));
        password_label3.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        password_label3.setText("Security Question");
        jPanel2.add(password_label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        firstname_label1.setBackground(new java.awt.Color(105, 73, 50));
        firstname_label1.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        firstname_label1.setText("First Name:");
        jPanel2.add(firstname_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 100, 20));

        invalid_password.setBackground(new java.awt.Color(105, 73, 50));
        invalid_password.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        invalid_password.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(invalid_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 259, 20));

        invalid_confirm.setBackground(new java.awt.Color(105, 73, 50));
        invalid_confirm.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        invalid_confirm.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(invalid_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 223, 20));

        invalid_sec.setBackground(new java.awt.Color(105, 73, 50));
        invalid_sec.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        invalid_sec.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(invalid_sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 211, 20));

        invalid_address.setBackground(new java.awt.Color(105, 73, 50));
        invalid_address.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        invalid_address.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(invalid_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 269, 20));

        invalid_name.setBackground(new java.awt.Color(105, 73, 50));
        invalid_name.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        invalid_name.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(invalid_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 272, 20));

        invalid_contact.setBackground(new java.awt.Color(105, 73, 50));
        invalid_contact.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        invalid_contact.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(invalid_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 180, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void contactnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactnumActionPerformed

    private void contactnumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactnumKeyReleased
        // TODO add your handling code here:
        if (String.valueOf(contactnum.getText()).equals("0") || String.valueOf(contactnum.getText()).equals("9") || contactnum.getText().isEmpty()) {
            contactnum.setText("09");
        }
    }//GEN-LAST:event_contactnumKeyReleased

    private void return_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_btnActionPerformed
     gui mainmenu = new gui();
                this.dispose();
                mainmenu.setVisible(true);

    }//GEN-LAST:event_return_btnActionPerformed

    private void signup_finish_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_finish_btnActionPerformed

String email = email_txt.getText().trim();
String password = password_txt.getText();
String confirmPassword = password_confirm_txt.getText();
String firstName = fname.getText().trim();
String lastName = lname.getText().trim();
String secAnswer = sec_ans.getText().trim();
String address = address_txt.getText().trim();
String contact = contactnum.getText().trim();
String secCode = jComboBox1.getSelectedItem().toString();
StringBuilder errors = new StringBuilder();

if (email.isEmpty() || 
   !(email.endsWith("@gmail.com") || email.endsWith("@yahoo.com") || email.endsWith("@ue.edu.ph"))) {
   invalid_email.setText("Invalid email.\n");
   errors.append("1");
}else{
    invalid_email.setText(null);
}

if (password.length() < 8 || password.length() > 30) {
    invalid_password.setText("Password must be 8 to 30 characters.\n");
    errors.append("2");
}else{
    invalid_password.setText(null);}
if (!password.equals(confirmPassword)) {
    invalid_confirm.setText("Passwords do not match.\n");
    errors.append("3");
}else{
    invalid_confirm.setText(null);}

if (firstName.isEmpty() || lastName.isEmpty()) {
   invalid_name.setText("Name fields can't be empty.\n");
   errors.append("4");
}else{
    invalid_name.setText(null);}

if (secAnswer.isEmpty()) {
   invalid_sec.setText("Security answer required.\n");
   errors.append("5");
}else{
    invalid_sec.setText(null);}

if (address.isEmpty()) {
    invalid_address.setText("Address is required.\n");
    errors.append("6");
}else{
    invalid_address.setText(null);}

if (contact.length() != 11 || !contact.matches("\\d+")) {
    invalid_contact.setText("Contact number must be exactly 11 digits.\n");
    errors.append("7");
}else{
    invalid_contact.setText(null);}
if (errors.length() > 0) {
    return;
}

try {
    String checkQuery = "SELECT 1 FROM users WHERE EMAIL = ?";
    try (PreparedStatement checkStmt = con.prepareStatement(checkQuery)) {
        checkStmt.setString(1, email);
        try (ResultSet rsCheck = checkStmt.executeQuery()) {
            if (rsCheck.next()) {
                JOptionPane.showMessageDialog(this, "Email already exists.", "Duplicate Email", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }
    String insertSQL = "INSERT INTO users (FIRSTNAME, LASTNAME, EMAIL, PASSWORD, SEC_ANSWER, SEC_CODE, ADDRESS, CONTACTNUM) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
    try (PreparedStatement pstmt = con.prepareStatement(insertSQL)) {
        pstmt.setString(1, firstName);
        pstmt.setString(2, lastName);
        pstmt.setString(3, email);
        pstmt.setString(4, password); 
        pstmt.setString(5, secAnswer);
        pstmt.setString(6, secCode);
        pstmt.setString(7, address);
        pstmt.setString(8, contact);
        con.setAutoCommit(true);
        int rowsInserted = pstmt.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "User registered successfully!");
            login mainmenu = new login();
                this.dispose();
                mainmenu.setVisible(true);
            Refresh_RS_STMT();
        } else {
            JOptionPane.showMessageDialog(this, "Something went wrong. Try again.");
        }
    }

} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
}
    }//GEN-LAST:event_signup_finish_btnActionPerformed

    private void address_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_txtActionPerformed

    private void email_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txtActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void sec_ansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sec_ansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sec_ansActionPerformed

    private void password_confirm_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_confirm_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_confirm_txtActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sign_in().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address_label;
    private javax.swing.JTextField address_txt;
    private javax.swing.JTextField contactnum;
    private javax.swing.JLabel contactnum_label;
    private javax.swing.JLabel email_label;
    private javax.swing.JTextField email_txt;
    private javax.swing.JLabel firstname_label1;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel invalid_address;
    private javax.swing.JLabel invalid_confirm;
    private javax.swing.JLabel invalid_contact;
    private javax.swing.JLabel invalid_email;
    private javax.swing.JLabel invalid_name;
    private javax.swing.JLabel invalid_password;
    private javax.swing.JLabel invalid_sec;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lastname_label;
    private javax.swing.JTextField lname;
    private javax.swing.JPasswordField password_confirm_txt;
    private javax.swing.JLabel password_label1;
    private javax.swing.JLabel password_label2;
    private javax.swing.JLabel password_label3;
    private javax.swing.JPasswordField password_txt;
    private javax.swing.JButton return_btn;
    private javax.swing.JTextField sec_ans;
    private javax.swing.JButton signup_finish_btn;
    // End of variables declaration//GEN-END:variables
}
